import React from 'react';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';

interface Pillar { id:string; title:string; core:string; actions:string[]; outcomes:string[]; impact:string; }
const PILLARS: Pillar[] = [
  { id:'intervention-ladder', title:'1. Intervention Ladder Discipline', core:'Escalate cost & complexity only after cheaper paths exhausted', actions:['Prompt / retrieval tuning first','Semantic cache + reuse','Selective routing before fine-tune'], outcomes:['Lower TCO curve slope','Reduced premature fine-tunes','Higher marginal lift per $'], impact:'Prevents runaway complexity & spend.' },
  { id:'routing-economics', title:'2. Routing & Arbitration Economics', core:'Match query complexity to cheapest adequate model', actions:['Complexity scoring features','A/B + interleaving validation','Fallback only on failure signals'], outcomes:['High-cost model usage <20%','Stable quality at lower avg cost','Better latency for simple tasks'], impact:'Optimizes blended cost / performance frontier.' },
  { id:'cache-strategy', title:'3. Integrity-Preserving Caching', core:'Reduce duplicate inference without stale answer risk', actions:['Similarity + freshness gating','Domain aware composite keys','Invalidation hooks on data change'], outcomes:['Hit rate >40% with <2% staleness','Reduced token spend volatility','Predictable cost forecasting'], impact:'Yields sustainable savings with trust retention.' },
  { id:'marginal-lift', title:'4. Marginal Lift Accountability', core:'Quantify ROI of each optimization layer', actions:['Pre/post lift dashboards','Cost per successful task metric','Sunset underperforming interventions'], outcomes:['Faster pruning of low ROI work','Higher confidence in scaling decisions','Transparent budget governance'], impact:'Channels investment to compounding levers.' }
];
export default function AICostValuePillars(){
  return <div className='space-y-8'>
    <Card><CardHeader><CardTitle>AI Cost & Value Engineering: 4 Pillars</CardTitle><CardDescription>Guardrails for sustainable economic performance.</CardDescription></CardHeader><CardContent className='grid md:grid-cols-2 gap-4'>{PILLARS.map(p=> <a key={p.id} href={'#'+p.id} className='p-4 rounded border hover:bg-muted/40 transition'><div className='font-semibold'>{p.title}</div><div className='text-xs text-muted-foreground line-clamp-2'>{p.core}</div></a>)}</CardContent></Card>
    {PILLARS.map(p=> <Card key={p.id} id={p.id} className='scroll-mt-24'><CardHeader><div className='flex items-center gap-2'><CardTitle>{p.title}</CardTitle><Badge variant='secondary'>{p.core.split(' ')[0]}</Badge></div><CardDescription>{p.core}</CardDescription></CardHeader><CardContent className='space-y-5'><div><h4 className='font-semibold mb-2'>Actions</h4><ul className='list-disc pl-5 space-y-1 text-sm'>{p.actions.map(a=> <li key={a}>{a}</li>)}</ul></div><div><h4 className='font-semibold mb-2'>Outcomes</h4><ul className='list-disc pl-5 space-y-1 text-sm'>{p.outcomes.map(o=> <li key={o}>{o}</li>)}</ul></div><div className='p-3 rounded border bg-background/60'><h4 className='font-semibold mb-1'>Impact</h4><p className='text-sm text-muted-foreground'>{p.impact}</p></div><div className='text-right'><a href='#top' className='text-xs text-muted-foreground hover:underline'>Back to top</a></div></CardContent></Card>)}
    <Card><CardHeader><CardTitle>Adoption Sequence</CardTitle><CardDescription>Economic maturity layering.</CardDescription></CardHeader><CardContent><ol className='list-decimal pl-5 space-y-1 text-sm'><li>Baseline Intervention Ladder</li><li>Routing Economics</li><li>Cache Integrity</li><li>Marginal Lift Analytics</li></ol></CardContent></Card>
  </div>;
}
