import React from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { ArrowRight, ArrowSquareOut, ChartBar } from "@phosphor-icons/react"

interface Props {
  onNavigate: () => void
}

export default function InteractiveVisualizations({ onNavigate }: Props) {
  return (
    <div className="space-y-6">
      {/* Introduction */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <ChartBar className="w-5 h-5" />
            Interactive AI-Native Practice Explorations
          </CardTitle>
          <CardDescription>
            Dive deep into real-world AI-native practices with interactive mindmaps 
            from OpenAI's Codex team and Anthropic's Claude Code teams
          </CardDescription>
        </CardHeader>
        <CardContent>
          <p className="text-lg leading-relaxed mb-6">
            These interactive visualizations let you explore how industry-leading organizations 
            structure their human-AI collaborative workflows. Click on nodes to expand sections and discover 
            the specific practices that are revolutionizing software development through partnership.
          </p>
        </CardContent>
      </Card>

      {/* OpenAI Codex Visualization */}
  <Card className="w-full bg-card">
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-lg bg-gradient-to-br from-emerald-400 to-blue-500 flex items-center justify-center">
                <span className="text-white font-bold text-lg">AI</span>
              </div>
              <div>
                <CardTitle>OpenAI Codex Team Practices</CardTitle>
                <CardDescription>Collaborative development workflows pioneered by the Codex team</CardDescription>
              </div>
            </div>
            <div className="flex gap-2">
              <Badge variant="secondary">7 Core Practices</Badge>
              <Badge variant="outline">Interactive</Badge>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <div className="flex flex-wrap gap-2 mb-4">
              <Badge variant="secondary">Ask Mode Bug Detection</Badge>
              <Badge variant="secondary">Mass Code Changes + PR Automation</Badge>
              <Badge variant="secondary">5-Minute Performance Audits</Badge>
              <Badge variant="secondary">Autogenerated Test PRs</Badge>
              <Badge variant="secondary">Async AI Work During Meetings</Badge>
            </div>
            
            <div className="border rounded-lg overflow-hidden bg-card">
              <iframe
                src="/visualizations/openai-codex-mindmap.html"
                width="100%"
                height="800"
                style={{ border: 'none' }}
                title="OpenAI Codex Mind Map - Interactive Exploration of AI-Native Development Practices"
                className="w-full"
              />
            </div>
            
            <div className="flex items-center justify-between pt-4">
              <p className="text-sm text-muted-foreground">
                <strong>Instructions:</strong> Click on any node to expand and explore deeper 
                into the specific practices that are revolutionizing software development.
              </p>
              <a
                href="https://openai.com/codex"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 text-sm text-blue-600 dark:text-blue-400 hover:underline"
              >
                <span>Learn more about Codex</span>
                <ArrowSquareOut className="w-4 h-4" />
              </a>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Anthropic Claude Code Visualization */}
  <Card className="w-full bg-card">
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-lg bg-gradient-to-br from-orange-400 to-red-500 flex items-center justify-center">
                <span className="text-white font-bold text-lg">A</span>
              </div>
              <div>
                <CardTitle>Anthropic Claude Code Team Practices</CardTitle>
                <CardDescription>Human-AI collaborative workflows transforming organizations together</CardDescription>
              </div>
            </div>
            <div className="flex gap-2">
              <Badge variant="secondary">10 Team Practices</Badge>
              <Badge variant="outline">Interactive</Badge>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <div className="flex flex-wrap gap-2 mb-4">
              <Badge variant="secondary">Screenshot-based Debugging</Badge>
              <Badge variant="secondary">70% AI Feature Development</Badge>
              <Badge variant="secondary">Non-Coder Workflow Execution</Badge>
              <Badge variant="secondary">Auto-Accept Loops</Badge>
              <Badge variant="secondary">Designer State Code Management</Badge>
            </div>
            
            <div className="border rounded-lg overflow-hidden bg-card">
              <iframe
                src="/visualizations/claude-code-mindmap.html"
                width="100%"
                height="800"
                style={{ border: 'none' }}
                title="Claude Code Mind Map - Interactive Exploration of Anthropic's AI-Native Practices"
                className="w-full"
              />
            </div>
            
            <div className="flex items-center justify-between pt-4">
              <p className="text-sm text-muted-foreground">
                <strong>Instructions:</strong> Click on team nodes to expand and see their specific practices 
                and learn how they're transforming their workflows with AI.
              </p>
              <a
                href="https://www.anthropic.com/news/how-anthropic-teams-use-claude-code"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 text-sm text-blue-600 dark:text-blue-400 hover:underline"
              >
                <span>How Anthropic uses Claude Code</span>
                <ArrowSquareOut className="w-4 h-4" />
              </a>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Key Insights */}
      <Card>
        <CardHeader>
          <CardTitle>Key Insights from Interactive Exploration</CardTitle>
          <CardDescription>
            What to look for when exploring these AI-native practice visualizations
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-4">
              <h3 className="text-lg font-semibold text-emerald-600 dark:text-emerald-400">OpenAI Codex Patterns</h3>
              <ul className="space-y-2 text-sm">
                <li className="flex items-start gap-2">
                  <span className="w-2 h-2 rounded-full bg-emerald-500 mt-2"></span>
                  <span><strong>Developer-Centric:</strong> Focus on individual productivity and code quality</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="w-2 h-2 rounded-full bg-emerald-500 mt-2"></span>
                  <span><strong>Async Workflows:</strong> Human-AI collaboration continues during meetings and downtime</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="w-2 h-2 rounded-full bg-emerald-500 mt-2"></span>
                  <span><strong>Quality Emphasis:</strong> Automated testing and performance optimization</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="w-2 h-2 rounded-full bg-emerald-500 mt-2"></span>
                  <span><strong>Flow State:</strong> Maintaining context and avoiding interruptions</span>
                </li>
              </ul>
            </div>

            <div className="space-y-4">
              <h3 className="text-lg font-semibold text-orange-600 dark:text-orange-400">Anthropic Claude Patterns</h3>
              <ul className="space-y-2 text-sm">
                <li className="flex items-start gap-2">
                  <span className="w-2 h-2 rounded-full bg-orange-500 mt-2"></span>
                  <span><strong>Cross-Functional:</strong> Empowering non-technical teams with AI capabilities</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="w-2 h-2 rounded-full bg-orange-500 mt-2"></span>
                  <span><strong>Collaborative AI:</strong> Human-guided AI agents enhancing team capabilities</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="w-2 h-2 rounded-full bg-orange-500 mt-2"></span>
                  <span><strong>Organizational Scale:</strong> Human-led teams transforming departments with AI partners</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="w-2 h-2 rounded-full bg-orange-500 mt-2"></span>
                  <span><strong>Visual Interfaces:</strong> Screenshot-based debugging and visual workflows</span>
                </li>
              </ul>
            </div>
          </div>

          <div className="mt-6 p-4 bg-blue-100 dark:bg-blue-900 border border-blue-200 dark:border-blue-800 rounded-lg">
            <h4 className="font-semibold text-blue-900 dark:text-blue-100 mb-2">🎯 Exploration Tips</h4>
            <ul className="text-sm text-blue-800 dark:text-blue-200 space-y-1">
              <li>• Start with high-level nodes, then drill down into specific practices</li>
              <li>• Compare similar practices between OpenAI and Anthropic approaches</li>
              <li>• Look for patterns that could apply to your organization</li>
              <li>• Note the progression from individual to team to organizational transformation</li>
            </ul>
          </div>

          <div className="mt-6 pt-6 border-t">
            <Button className="w-full" size="lg" onClick={onNavigate}>
              <span>Next: Code Understanding</span>
              <ArrowRight className="w-4 h-4 ml-2" />
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
