name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout repository
        run: |
          git clone --depth=1 ${{ github.server_url }}/${{ github.repository }}.git .
          git checkout ${{ github.sha }}
      
      - name: Setup Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
      
      - name: Install dependencies
        run: |
          npm ci
      
      - name: Build application
        run: |
          npm run build
      
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      
      - name: Install Static Web Apps CLI
        run: |
          npm install -g @azure/static-web-apps-cli
      
      - name: Deploy to Azure Static Web Apps
        env:
          SWA_CLI_DEPLOYMENT_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_FLOWER_04EC3A31E }}
        run: |
          npx swa deploy ./dist --deployment-token $SWA_CLI_DEPLOYMENT_TOKEN --env production

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      
      - name: Install Static Web Apps CLI
        run: |
          npm install -g @azure/static-web-apps-cli
      
      - name: Close Pull Request Environment
        env:
          SWA_CLI_DEPLOYMENT_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_FLOWER_04EC3A31E }}
        run: |
          echo "Pull request closed - cleaning up preview environment"
          # Note: The SWA CLI doesn't have a direct "close" command like the action
          # Preview environments are automatically cleaned up when PRs are closed
